export const nameToAbbrev: Record<string, string> = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  'Canal Zone': 'CZ',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  'District of Columbia': 'DC',
  Florida: 'FL',
  Georgia: 'GA',
  Guam: 'GU',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Puerto Rico': 'PR',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  'Virgin Islands': 'VI',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
};

export const AbbrevToName: Record<string, string> = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CZ: 'Canal Zone',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  GU: 'Guam',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VI: 'Virgin Islands',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};

export const nameToStandard: Record<string, string> = {
  Alabama: 'Ala.',
  Alaska: 'Alaska',
  Arizona: 'Ariz.',
  Arkansas: 'Ark.',
  California: 'Calif.',
  'Canal Zone': 'C.Z.',
  Colorado: 'Colo.',
  Connecticut: 'Conn.',
  Delaware: 'Del.',
  'District of Columbia': 'D.C.',
  Florida: 'Fla.',
  Georgia: 'Ga.',
  Guam: 'Guam',
  Hawaii: 'Hawaii',
  Idaho: 'Idaho',
  Illinois: 'Ill.',
  Indiana: 'Ind.',
  Iowa: 'Iowa',
  Kansas: 'Kan.',
  Kentucky: 'Ky.',
  Louisiana: 'La.',
  Maine: 'Maine',
  Maryland: 'Md.',
  Massachusetts: 'Mass.',
  Michigan: 'Mich.',
  Minnesota: 'Minn.',
  Mississippi: 'Miss.',
  Missouri: 'Mo.',
  Montana: 'Mont.',
  Nebraska: 'Neb.',
  Nevada: 'Nev.',
  'New Hampshire': 'N.H.',
  'New Jersey': 'N.J.',
  'New Mexico': 'N.M.',
  'New York': 'N.Y.',
  'North Carolina': 'N.C.',
  'North Dakota': 'N.D.',
  Ohio: 'Ohio',
  Oklahoma: 'Okla.',
  Oregon: 'Ore.',
  Pennsylvania: 'Pa.',
  'Puerto Rico': 'P.R.',
  'Rhode Island': 'R.I.',
  'South Carolina': 'S.C.',
  'South Dakota': 'S.D.',
  Tennessee: 'Tenn.',
  Texas: 'Texas',
  Utah: 'Utah',
  Vermont: 'Vt.',
  'Virgin Islands': 'V.I.',
  Virginia: 'Va.',
  Washington: 'Wash.',
  'West Virginia': 'W.Va.',
  Wisconsin: 'Wis.',
  Wyoming: 'Wyo.',
};
